module StringTest
{
	typedef string Name;
	typedef sequence< Name > NameSeq;

	typedef Name NameID;
	typedef sequence< NameID > NameIDSeq;

	struct StructWithStrings
	{
		string str;
		Name nam;
		NameID id;
	};

	interface InterfaceString
	{
		void operation1(in string s);
		void operation2(in Name n);
		void operation3(in NameSeq n);
		void operation4(in StructWithStrings n);

		void operation5(in NameID n);
		void operation6(in NameIDSeq n);
	};
};

