
module MyModule
{

    enum MyEnum
    {
        AAA,
        BBB,
        CCC
    };

    union MyUnion switch(MyEnum)
    {
        case AAA :
            long one;
        case BBB :
        case CCC :
            long other;
    };

    union MyUnion2 switch(long)
    {
        case 100 :
            MyUnion one;
        case 200 :
            long other;
    };

    union MyUnion3 switch(boolean)
    {
        case TRUE :
            MyUnion one;
        case FALSE :
            long other;
    };

    struct MyStruct
    {
        long a[11];
    };

    interface MyInterface
    {
        void operation(in MyUnion uni);
        void operation1(in MyUnion2 uni);
        void operation2(in MyStruct uni);
        void operation3(in MyUnion3 uni);
    };

};

