
module MyModule
{

    enum MyEnum
    {
        AAA,
        BBB,
        CCC
    };

    union MyUnion switch(MyEnum)
    {
        case AAA :
            long one;
        case BBB :
        case CCC :
            long other;
    };


    struct MyStruct
    {
        long a[11];
    };

    interface MyInterface
    {
        void operation(in MyUnion uni);
        void operation2(in MyStruct uni);
    };

};

