module HelloApp
{
  typedef sequence< string > Names;
  interface Hello
  {
    string sayHello();
    string sayHelloTo(in Names people);
    oneway void shutdown();
  };
};

module Test { interface Huge {
    oneway void operation1(in long a);
    oneway void operation2(in long a);
    oneway void operation3(in long a);
    oneway void operation4(in long a);
    oneway void operation5(in long a);
    oneway void operation6(in long a);
    oneway void operation7(in long a);
    oneway void operation8(in long a);
    oneway void operation9(in long a);
    oneway void operation10(in long a);
    oneway void operation11(in long a);
    oneway void operation12(in long a);
    oneway void operation13(in long a);
    oneway void operation14(in long a);
    oneway void operation15(in long a);
    oneway void operation16(in long a);
    oneway void operation17(in long a);
    oneway void operation18(in long a);
    oneway void operation19(in long a);
    oneway void operation20(in long a);
    oneway void operation21(in long a);
    oneway void operation22(in long a);
    oneway void operation23(in long a);
    oneway void operation24(in long a);
    oneway void operation25(in long a);
    oneway void operation26(in long a);
    oneway void operation27(in long a);
    oneway void operation28(in long a);
    oneway void operation29(in long a);
    oneway void operation30(in long a);
    oneway void operation31(in long a);
    oneway void operation32(in long a);
    oneway void operation33(in long a);
    oneway void operation34(in long a);
    oneway void operation35(in long a);
    oneway void operation36(in long a);
    oneway void operation37(in long a);
    oneway void operation38(in long a);
    oneway void operation39(in long a);
    oneway void operation40(in long a);
    oneway void operation41(in long a);
    oneway void operation42(in long a);
    oneway void operation43(in long a);
    oneway void operation44(in long a);
    oneway void operation45(in long a);
    oneway void operation46(in long a);
    oneway void operation47(in long a);
    oneway void operation48(in long a);
    oneway void operation49(in long a);
    oneway void operation50(in long a);
    oneway void operation51(in long a);
    oneway void operation52(in long a);
    oneway void operation53(in long a);
    oneway void operation54(in long a);
    oneway void operation55(in long a);
    oneway void operation56(in long a);
    oneway void operation57(in long a);
    oneway void operation58(in long a);
    oneway void operation59(in long a);
    oneway void operation60(in long a);
    oneway void operation61(in long a);
    oneway void operation62(in long a);
    oneway void operation63(in long a);
    oneway void operation64(in long a);
    oneway void operation65(in long a);
    oneway void operation66(in long a);
    oneway void operation67(in long a);
    oneway void operation68(in long a);
    oneway void operation69(in long a);
    oneway void operation70(in long a);
    oneway void operation71(in long a);
    oneway void operation72(in long a);
    oneway void operation73(in long a);
    oneway void operation74(in long a);
    oneway void operation75(in long a);
    oneway void operation76(in long a);
    oneway void operation77(in long a);
    oneway void operation78(in long a);
    oneway void operation79(in long a);
    oneway void operation80(in long a);
    oneway void operation81(in long a);
    oneway void operation82(in long a);
    oneway void operation83(in long a);
    oneway void operation84(in long a);
    oneway void operation85(in long a);
    oneway void operation86(in long a);
    oneway void operation87(in long a);
    oneway void operation88(in long a);
    oneway void operation89(in long a);
    oneway void operation90(in long a);
    oneway void operation91(in long a);
    oneway void operation92(in long a);
    oneway void operation93(in long a);
    oneway void operation94(in long a);
    oneway void operation95(in long a);
    oneway void operation96(in long a);
    oneway void operation97(in long a);
    oneway void operation98(in long a);
    oneway void operation99(in long a);
    oneway void operation100(in long a);
    oneway void operation101(in long a);
    oneway void operation102(in long a);
    oneway void operation103(in long a);
    oneway void operation104(in long a);
    oneway void operation105(in long a);
    oneway void operation106(in long a);
    oneway void operation107(in long a);
    oneway void operation108(in long a);
    oneway void operation109(in long a);
    oneway void operation110(in long a);
    oneway void operation111(in long a);
    oneway void operation112(in long a);
    oneway void operation113(in long a);
    oneway void operation114(in long a);
    oneway void operation115(in long a);
    oneway void operation116(in long a);
    oneway void operation117(in long a);
    oneway void operation118(in long a);
    oneway void operation119(in long a);
    oneway void operation120(in long a);
    oneway void operation121(in long a);
    oneway void operation122(in long a);
    oneway void operation123(in long a);
    oneway void operation124(in long a);
    oneway void operation125(in long a);
    oneway void operation126(in long a);
    oneway void operation127(in long a);
    oneway void operation128(in long a);
    oneway void operation129(in long a);
    oneway void operation130(in long a);
    oneway void operation131(in long a);
    oneway void operation132(in long a);
    oneway void operation133(in long a);
    oneway void operation134(in long a);
    oneway void operation135(in long a);
    oneway void operation136(in long a);
    oneway void operation137(in long a);
    oneway void operation138(in long a);
    oneway void operation139(in long a);
    oneway void operation140(in long a);
    oneway void operation141(in long a);
    oneway void operation142(in long a);
    oneway void operation143(in long a);
    oneway void operation144(in long a);
    oneway void operation145(in long a);
    oneway void operation146(in long a);
    oneway void operation147(in long a);
    oneway void operation148(in long a);
    oneway void operation149(in long a);
    oneway void operation150(in long a);
    oneway void operation151(in long a);
    oneway void operation152(in long a);
    oneway void operation153(in long a);
    oneway void operation154(in long a);
    oneway void operation155(in long a);
    oneway void operation156(in long a);
    oneway void operation157(in long a);
    oneway void operation158(in long a);
    oneway void operation159(in long a);
    oneway void operation160(in long a);
    oneway void operation161(in long a);
    oneway void operation162(in long a);
    oneway void operation163(in long a);
    oneway void operation164(in long a);
    oneway void operation165(in long a);
    oneway void operation166(in long a);
    oneway void operation167(in long a);
    oneway void operation168(in long a);
    oneway void operation169(in long a);
    oneway void operation170(in long a);
    oneway void operation171(in long a);
    oneway void operation172(in long a);
    oneway void operation173(in long a);
    oneway void operation174(in long a);
    oneway void operation175(in long a);
    oneway void operation176(in long a);
    oneway void operation177(in long a);
    oneway void operation178(in long a);
    oneway void operation179(in long a);
    oneway void operation180(in long a);
    oneway void operation181(in long a);
    oneway void operation182(in long a);
    oneway void operation183(in long a);
    oneway void operation184(in long a);
    oneway void operation185(in long a);
    oneway void operation186(in long a);
    oneway void operation187(in long a);
    oneway void operation188(in long a);
    oneway void operation189(in long a);
    oneway void operation190(in long a);
    oneway void operation191(in long a);
    oneway void operation192(in long a);
    oneway void operation193(in long a);
    oneway void operation194(in long a);
    oneway void operation195(in long a);
    oneway void operation196(in long a);
    oneway void operation197(in long a);
    oneway void operation198(in long a);
    oneway void operation199(in long a);
};
};


module AAAAAAAAA
{

    struct ESS
    {
        string a;
    };

    typedef sequence< ESS > EEESeq;

    typedef long aaaaa[100];

    interface IIIIIIIIII
    {
        EEESeq op1();
        ESS op2();

    };

};


module SimpleExample
{

    union MyUnion switch(long)
    {
        case 100: long aa;
        case 101: long bb;
    };

    struct St
    {

        sequence< long > l;
        sequence< string > ss;
        long b;
        MyUnion uniii;
    };

    interface Test
    {
        oneway void operation1(in long a, in long b, in St c);

        typedef long a_t[100];




        void operation4(in Test a);




    };

    struct Hijo
    {
        long b;
        boolean l;
        string s;
    };

    struct Padre
    {
        Hijo h;
    };

    typedef Padre Padres[10];

    struct Abuelo
    {
        Padres p;
        Test tt;
    };
};
module StringTest
{
 typedef string Name;
 typedef sequence< Name > NameSeq;
 typedef sequence< string > StringSeq;

 typedef Name NameID;
 typedef sequence< NameID > NameIDSeq;

 struct StructWithStrings
 {
  string str;
  Name nam;
  NameID id;
 };

 interface InterfaceString
 {
  void operation1(in string s);
  void operation2(in Name n);
  void operation3(in NameSeq n);
  void operation4(in StructWithStrings n);
  void operation5(in NameID n);
  void operation6(in NameIDSeq n);
  void operation7(in StringSeq n);
 };
};


module MyModule
{

    enum MyEnum
    {
        AAA,
        BBB,
        CCC
    };

    union MyUnion switch(MyEnum)
    {
        case AAA :
            long one;
        case BBB :
        case CCC :
            long other;
    };

    union MyUnion2 switch(long)
    {
        case 100 :
            MyUnion one;
        case 200 :
            long other;
    };

    union MyUnion3 switch(boolean)
    {
        case TRUE :
            MyUnion one;
        case FALSE :
            long other;
    };

    struct MyStruct
    {
        long a[11];
    };

    interface MyInterface
    {
        void operation(in MyUnion uni);
        void operation1(in MyUnion2 uni);
        void operation2(in MyStruct uni);
        void operation3(in MyUnion3 uni);
    };

};


module Test
{

    interface Prueba;

    struct St
    {
        string a;
        string b;
        Prueba reffff;
    };

    struct St2
    {
        St a;
        St b;
        string c;
        long unsupported;
    };

    interface Prueba
    {
        oneway void operacion1(in St2 a, in St b);
        oneway void operacion2(in Prueba myref);
        oneway void operacion3();
    };

};
