
module AAAAAAAAA
{

    struct ESS
    {
        string a;
    };

    typedef sequence< ESS > EEESeq;

    typedef long aaaaa[100];

    interface IIIIIIIIII
    {
        EEESeq op1();
        ESS op2();
        // aaaaa op3();
    };

};

