
module Test
{

    interface Prueba;

    struct St
    {
        string a;
        string b;
        Prueba reffff;
    };

    struct St2
    {
        St a;
        St b;
        string c;
        long unsupported;
    };

    interface Prueba
    {
        oneway void operacion1(in St2 a, in St b);
        oneway void operacion2(in Prueba myref);
        oneway void operacion3();
    };

};

