// This file was GENERATED by command:
//     pump.py vectorX.hpp.pump
// DO NOT EDIT BY HAND!!!

// -*- mode: c++; c-basic-style: "bsd"; c-basic-offset: 4; -*-
/*
 * vector.hpp
 * Copyright (C) Cátedra SAES-UMU 2011 <catedra-saes-umu@listas.um.es>
 *
 * CORBASIM is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CORBASIM is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef CORBASIM_MPL_VECTOR_HPP
#define CORBASIM_MPL_VECTOR_HPP

#include <boost/mpl/int.hpp>

namespace corbasim
{
namespace cs_mpl
{
namespace detail
{
struct none {};
} // namespace detail

template <  typename P0 = detail::none ,  typename P1 = detail::none ,
    typename P2 = detail::none ,  typename P3 = detail::none ,
    typename P4 = detail::none ,  typename P5 = detail::none ,
    typename P6 = detail::none ,  typename P7 = detail::none ,
    typename P8 = detail::none ,  typename P9 = detail::none ,
    typename P10 = detail::none ,  typename P11 = detail::none ,
    typename P12 = detail::none ,  typename P13 = detail::none ,
    typename P14 = detail::none ,  typename P15 = detail::none ,
    typename P16 = detail::none ,  typename P17 = detail::none ,
    typename P18 = detail::none ,  typename P19 = detail::none ,
    typename P20 = detail::none ,  typename P21 = detail::none ,
    typename P22 = detail::none ,  typename P23 = detail::none ,
    typename P24 = detail::none ,  typename P25 = detail::none ,
    typename P26 = detail::none ,  typename P27 = detail::none ,
    typename P28 = detail::none ,  typename P29 = detail::none ,
    typename P30 = detail::none ,  typename P31 = detail::none ,
    typename P32 = detail::none ,  typename P33 = detail::none ,
    typename P34 = detail::none ,  typename P35 = detail::none ,
    typename P36 = detail::none ,  typename P37 = detail::none ,
    typename P38 = detail::none ,  typename P39 = detail::none ,
    typename P40 = detail::none ,  typename P41 = detail::none ,
    typename P42 = detail::none ,  typename P43 = detail::none ,
    typename P44 = detail::none ,  typename P45 = detail::none ,
    typename P46 = detail::none ,  typename P47 = detail::none ,
    typename P48 = detail::none ,  typename P49 = detail::none  >
struct vector
{
    typedef boost::mpl::int_< 50 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43 ,  P44 ,  P45 ,  P46 ,  P47 ,  P48 ,  P49
        > tail_type;
};

template < >
struct vector<  detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none ,  detail::none ,  detail::none ,
    detail::none ,  detail::none  >
{
    typedef boost::mpl::int_< 0 > size_type;
};

template <  typename P0  >
struct vector <  P0,      /* P1 */ detail::none ,  /* P2 */ detail::none ,
    /* P3 */ detail::none ,  /* P4 */ detail::none ,  /* P5 */ detail::none ,
    /* P6 */ detail::none ,  /* P7 */ detail::none ,  /* P8 */ detail::none ,
    /* P9 */ detail::none ,  /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 1 > size_type;
    typedef P0 head_type;
    typedef vector<
        > tail_type;
};

template <  typename P0 ,  typename P1  >
struct vector <  P0,  P1,      /* P2 */ detail::none ,  /* P3 */ detail::none ,
    /* P4 */ detail::none ,  /* P5 */ detail::none ,  /* P6 */ detail::none ,
    /* P7 */ detail::none ,  /* P8 */ detail::none ,  /* P9 */ detail::none ,
    /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 2 > size_type;
    typedef P0 head_type;
    typedef vector<  P1
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2  >
struct vector <  P0,  P1,  P2,      /* P3 */ detail::none ,
    /* P4 */ detail::none ,  /* P5 */ detail::none ,  /* P6 */ detail::none ,
    /* P7 */ detail::none ,  /* P8 */ detail::none ,  /* P9 */ detail::none ,
    /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 3 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3  >
struct vector <  P0,  P1,  P2,  P3,      /* P4 */ detail::none ,
    /* P5 */ detail::none ,  /* P6 */ detail::none ,  /* P7 */ detail::none ,
    /* P8 */ detail::none ,  /* P9 */ detail::none ,  /* P10 */ detail::none ,
    /* P11 */ detail::none ,  /* P12 */ detail::none ,
    /* P13 */ detail::none ,  /* P14 */ detail::none ,
    /* P15 */ detail::none ,  /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 4 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4  >
struct vector <  P0,  P1,  P2,  P3,  P4,      /* P5 */ detail::none ,
    /* P6 */ detail::none ,  /* P7 */ detail::none ,  /* P8 */ detail::none ,
    /* P9 */ detail::none ,  /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 5 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,      /* P6 */ detail::none ,
    /* P7 */ detail::none ,  /* P8 */ detail::none ,  /* P9 */ detail::none ,
    /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 6 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,      /* P7 */ detail::none ,
    /* P8 */ detail::none ,  /* P9 */ detail::none ,  /* P10 */ detail::none ,
    /* P11 */ detail::none ,  /* P12 */ detail::none ,
    /* P13 */ detail::none ,  /* P14 */ detail::none ,
    /* P15 */ detail::none ,  /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 7 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,
    /* P8 */ detail::none ,  /* P9 */ detail::none ,  /* P10 */ detail::none ,
    /* P11 */ detail::none ,  /* P12 */ detail::none ,
    /* P13 */ detail::none ,  /* P14 */ detail::none ,
    /* P15 */ detail::none ,  /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 8 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,
    /* P9 */ detail::none ,  /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 9 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,
    /* P10 */ detail::none ,  /* P11 */ detail::none ,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 10 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,
    /* P11 */ detail::none ,  /* P12 */ detail::none ,
    /* P13 */ detail::none ,  /* P14 */ detail::none ,
    /* P15 */ detail::none ,  /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 11 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,  P10
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    /* P12 */ detail::none ,  /* P13 */ detail::none ,
    /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 12 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,      /* P13 */ detail::none ,  /* P14 */ detail::none ,
    /* P15 */ detail::none ,  /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 13 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,      /* P14 */ detail::none ,  /* P15 */ detail::none ,
    /* P16 */ detail::none ,  /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 14 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,      /* P15 */ detail::none ,  /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 15 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,      /* P16 */ detail::none ,
    /* P17 */ detail::none ,  /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 16 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,      /* P17 */ detail::none ,
    /* P18 */ detail::none ,  /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 17 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,      /* P18 */ detail::none ,
    /* P19 */ detail::none ,  /* P20 */ detail::none ,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 18 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,      /* P19 */ detail::none ,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 19 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,
    /* P20 */ detail::none ,  /* P21 */ detail::none ,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 20 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,
    /* P21 */ detail::none ,  /* P22 */ detail::none ,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 21 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,
    /* P22 */ detail::none ,  /* P23 */ detail::none ,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 22 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,
    /* P23 */ detail::none ,  /* P24 */ detail::none ,
    /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 23 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    /* P24 */ detail::none ,  /* P25 */ detail::none ,
    /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 24 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,      /* P25 */ detail::none ,  /* P26 */ detail::none ,
    /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 25 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,      /* P26 */ detail::none ,  /* P27 */ detail::none ,
    /* P28 */ detail::none ,  /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 26 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,      /* P27 */ detail::none ,  /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 27 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,      /* P28 */ detail::none ,
    /* P29 */ detail::none ,  /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 28 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,      /* P29 */ detail::none ,
    /* P30 */ detail::none ,  /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 29 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,      /* P30 */ detail::none ,
    /* P31 */ detail::none ,  /* P32 */ detail::none ,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 30 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,      /* P31 */ detail::none ,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 31 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,
    /* P32 */ detail::none ,  /* P33 */ detail::none ,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 32 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,
    /* P33 */ detail::none ,  /* P34 */ detail::none ,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 33 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,
    /* P34 */ detail::none ,  /* P35 */ detail::none ,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 34 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,
    /* P35 */ detail::none ,  /* P36 */ detail::none ,
    /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 35 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    /* P36 */ detail::none ,  /* P37 */ detail::none ,
    /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 36 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,      /* P37 */ detail::none ,  /* P38 */ detail::none ,
    /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 37 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,      /* P38 */ detail::none ,  /* P39 */ detail::none ,
    /* P40 */ detail::none ,  /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 38 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,      /* P39 */ detail::none ,  /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 39 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,      /* P40 */ detail::none ,
    /* P41 */ detail::none ,  /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 40 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,      /* P41 */ detail::none ,
    /* P42 */ detail::none ,  /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 41 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,      /* P42 */ detail::none ,
    /* P43 */ detail::none ,  /* P44 */ detail::none ,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 42 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,      /* P43 */ detail::none ,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 43 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42 ,  typename P43  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,  P43,
    /* P44 */ detail::none ,  /* P45 */ detail::none ,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 44 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42 ,  typename P43 ,  typename P44  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,  P43,  P44,
    /* P45 */ detail::none ,  /* P46 */ detail::none ,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 45 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43 ,  P44
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42 ,  typename P43 ,  typename P44 ,
    typename P45  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,  P43,  P44,  P45,
    /* P46 */ detail::none ,  /* P47 */ detail::none ,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 46 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43 ,  P44 ,  P45
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42 ,  typename P43 ,  typename P44 ,
    typename P45 ,  typename P46  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,  P43,  P44,  P45,  P46,
    /* P47 */ detail::none ,  /* P48 */ detail::none ,
    /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 47 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43 ,  P44 ,  P45 ,  P46
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42 ,  typename P43 ,  typename P44 ,
    typename P45 ,  typename P46 ,  typename P47  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,  P43,  P44,  P45,  P46,  P47,
    /* P48 */ detail::none ,  /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 48 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43 ,  P44 ,  P45 ,  P46 ,  P47
        > tail_type;
};

template <  typename P0 ,  typename P1 ,  typename P2 ,  typename P3 ,
    typename P4 ,  typename P5 ,  typename P6 ,  typename P7 ,  typename P8 ,
    typename P9 ,  typename P10 ,  typename P11 ,  typename P12 ,
    typename P13 ,  typename P14 ,  typename P15 ,  typename P16 ,
    typename P17 ,  typename P18 ,  typename P19 ,  typename P20 ,
    typename P21 ,  typename P22 ,  typename P23 ,  typename P24 ,
    typename P25 ,  typename P26 ,  typename P27 ,  typename P28 ,
    typename P29 ,  typename P30 ,  typename P31 ,  typename P32 ,
    typename P33 ,  typename P34 ,  typename P35 ,  typename P36 ,
    typename P37 ,  typename P38 ,  typename P39 ,  typename P40 ,
    typename P41 ,  typename P42 ,  typename P43 ,  typename P44 ,
    typename P45 ,  typename P46 ,  typename P47 ,  typename P48  >
struct vector <  P0,  P1,  P2,  P3,  P4,  P5,  P6,  P7,  P8,  P9,  P10,  P11,
    P12,  P13,  P14,  P15,  P16,  P17,  P18,  P19,  P20,  P21,  P22,  P23,
    P24,  P25,  P26,  P27,  P28,  P29,  P30,  P31,  P32,  P33,  P34,  P35,
    P36,  P37,  P38,  P39,  P40,  P41,  P42,  P43,  P44,  P45,  P46,  P47,
    P48,      /* P49 */ detail::none  >
{
    typedef boost::mpl::int_< 49 > size_type;
    typedef P0 head_type;
    typedef vector<  P1 ,  P2 ,  P3 ,  P4 ,  P5 ,  P6 ,  P7 ,  P8 ,  P9 ,
        P10 ,  P11 ,  P12 ,  P13 ,  P14 ,  P15 ,  P16 ,  P17 ,  P18 ,  P19 ,
        P20 ,  P21 ,  P22 ,  P23 ,  P24 ,  P25 ,  P26 ,  P27 ,  P28 ,  P29 ,
        P30 ,  P31 ,  P32 ,  P33 ,  P34 ,  P35 ,  P36 ,  P37 ,  P38 ,  P39 ,
        P40 ,  P41 ,  P42 ,  P43 ,  P44 ,  P45 ,  P46 ,  P47 ,  P48
        > tail_type;
};

} // namespace cs_mpl
} // namespace corbasim

#endif /* CORBASIM_MPL_VECTOR_HPP */

