// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.7.9
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// ../../../ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:451

#ifndef _TAO_IDL_RETURNS_GJ46UA_H_
#define _TAO_IDL_RETURNS_GJ46UA_H_


#include "returnC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// ../../../ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:41

namespace POA_AAAAAAAAA
{
  
  
  // TAO_IDL - Generated from
  // ../../../ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:78
  
  class IIIIIIIIII;
  typedef IIIIIIIIII *IIIIIIIIII_ptr;
  
  class  IIIIIIIIII
    : public virtual PortableServer::ServantBase
  {
  protected:
    IIIIIIIIII (void);
  
  public:
    // Useful for template programming.
    typedef ::AAAAAAAAA::IIIIIIIIII _stub_type;
    typedef ::AAAAAAAAA::IIIIIIIIII_ptr _stub_ptr_type;
    typedef ::AAAAAAAAA::IIIIIIIIII_var _stub_var_type;
    
    IIIIIIIIII (const IIIIIIIIII& rhs);
    virtual ~IIIIIIIIII (void);
    
    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
    
    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::AAAAAAAAA::IIIIIIIIII *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // ../../../ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:41
    
    virtual ::AAAAAAAAA::EEESeq * op1 (void) = 0;
    
    static void op1_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
    
    // TAO_IDL - Generated from
    // ../../../ACE_wrappers/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:41
    
    virtual ::AAAAAAAAA::ESS * op2 (void) = 0;
    
    static void op2_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

// TAO_IDL - Generated from
// ../../../ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:72

} // module AAAAAAAAA

// TAO_IDL - Generated from 
// ../../../ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1658


#if defined (__ACE_INLINE__)
#include "returnS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

