
module SimpleExample
{

    union MyUnion switch(long)
    {
        case 100: long aa;
        case 101: long bb;
    };

    struct St
    {
        // sequence< string > a;
        sequence< long > l;
        sequence< string > ss;
        long b;
        MyUnion uniii;
    };

    interface Test
    {
        oneway void operation1(in long a, in long b, in St c);

        typedef long a_t[100];

//        oneway void operation2(in a_t a);
//        void operation3(in Object a);

        void operation4(in Test a);

//        typedef sequence< Test > TestSeq;

//        void operation5(in TestSeq se);
    };

    struct Hijo
    {
        long b;
        boolean l;
        string s;
    };

    struct Padre
    {
        Hijo h;
    };

    typedef Padre Padres[10];

    struct Abuelo
    {
        Padres p;
        Test tt;
    };
};
